# Generated by Django 3.0.8 on 2020-08-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('picture', models.ImageField(null=True, upload_to=None)),
            ],
            options={
                'ordering': ['-content'],
            },
        ),
        migrations.CreateModel(
            name='UpdateProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('about', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
