# Generated by Django 3.0.8 on 2020-08-09 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retroNet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={},
        ),
    ]
